###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "asset": "BTC",
  "price": 10.06,
  "amount": 55,
  "direction": "BUY"
}


###
POST http://localhost:8080/orders
Content-Type: application/json

{
  "asset": "BTC",
  "price": 10.0,
  "amount": 55,
  "direction": "SELL"
}



###

<> 2025-05-27T235015.200.json
###
GET http://localhost:8080/orders/7


###
GET http://localhost:8080/orders/buy/BTC



###
GET http://localhost:8080/orders/sell/BTC

